# This file was generated by GoReleaser. DO NOT EDIT.
cask "workset@0.3" do
  version "0.3.0"

  on_macos do
    on_intel do
      url "https://github.com/strantalis/workset/releases/download/v#{version}/workset_#{version}_darwin_amd64.tar.gz"
      sha256 "cde8af7ba1e93c2bcb4f060818e86294639213cd95f6ca26e8b8556646efba0b"
    end
    on_arm do
      url "https://github.com/strantalis/workset/releases/download/v#{version}/workset_#{version}_darwin_arm64.tar.gz"
      sha256 "f9ffc3d5f07d2a94e7e044509d860d4006f9bb3133c7cfc5f8a38cef45b9a689"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/strantalis/workset/releases/download/v#{version}/workset_#{version}_linux_amd64.tar.gz"
      sha256 "870f11dc201905d89326994b1ae7e3b5dd7ff2da2e2578ea14aee15e55d7c5ef"
    end
    on_arm do
      url "https://github.com/strantalis/workset/releases/download/v#{version}/workset_#{version}_linux_arm64.tar.gz"
      sha256 "397fc0c1a57ba98c91d31d2e426d6cd4d6207785432a63bd105fe6393d6127b4"
    end
  end

  name "workset@0.3"
  desc "Go CLI for multi-repo workspaces with linked worktrees"
  homepage "https://workset.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "workset"

  # No zap stanza required

end
