# This file was generated by GoReleaser. DO NOT EDIT.
cask "workset" do
  version "0.3.1"

  on_macos do
    on_intel do
      url "https://github.com/strantalis/workset/releases/download/v#{version}/workset_#{version}_darwin_amd64.tar.gz"
      sha256 "916c02b38a404e185b5fab52cc596f433a7e8e468521763155e26b842f805cd2"
    end
    on_arm do
      url "https://github.com/strantalis/workset/releases/download/v#{version}/workset_#{version}_darwin_arm64.tar.gz"
      sha256 "ba3196d2508c2d5e63337ae3f05b6c1edb71e1f65dd60f331ee195b4955586d1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/strantalis/workset/releases/download/v#{version}/workset_#{version}_linux_amd64.tar.gz"
      sha256 "cb300a009a7b8343c9e6b961ebf76efa8d88cf759bfa1f883f523cf31e98487a"
    end
    on_arm do
      url "https://github.com/strantalis/workset/releases/download/v#{version}/workset_#{version}_linux_arm64.tar.gz"
      sha256 "70d6350e9db60b1f53c380e550a93baa348ab0672a052b1374133728b73fb3f4"
    end
  end

  name "workset"
  desc "Go CLI for multi-repo workspaces with linked worktrees"
  homepage "https://workset.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "workset"

  # No zap stanza required

end
