# This file was generated by GoReleaser. DO NOT EDIT.
cask "workset" do
  version "0.3.0"

  on_macos do
    on_intel do
      url "https://github.com/strantalis/workset/releases/download/v#{version}/workset_#{version}_darwin_amd64.tar.gz"
      sha256 "ff4f1e87b13aedda038bdcc42ac2097dcc999b8614b71533e017c1fc31e5b9a9"
    end
    on_arm do
      url "https://github.com/strantalis/workset/releases/download/v#{version}/workset_#{version}_darwin_arm64.tar.gz"
      sha256 "4db2efa98a22cf22817493ec30cf382210030e65103238403ab5027608adc45e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/strantalis/workset/releases/download/v#{version}/workset_#{version}_linux_amd64.tar.gz"
      sha256 "c0b0d69eb2543da7ecbf2615089ba8c5f4bf2b8cd6da45ff8a3fbbfe83011573"
    end
    on_arm do
      url "https://github.com/strantalis/workset/releases/download/v#{version}/workset_#{version}_linux_arm64.tar.gz"
      sha256 "5870d57c612e681cadde65c727f338fe37d0a5d1235330ef2fa516b748ff80ba"
    end
  end

  name "workset"
  desc "Go CLI for multi-repo workspaces with linked worktrees"
  homepage "https://workset.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "workset"

  # No zap stanza required

end
