# This file was generated by GoReleaser. DO NOT EDIT.
cask "workset@0.2" do
  name "workset@0.2"
  desc "Go CLI for multi-repo workspaces with linked worktrees"
  homepage "https://workset.dev"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "workset"

  on_macos do
    on_intel do
      url "https://github.com/strantalis/workset/releases/download/v#{version}/workset_#{version}_darwin_amd64.tar.gz"
      sha256 "b7d44e43770cffefaf2e3662a8b543abbf1a5abf235cf3c666fed1c1052afdb9"
    end
    on_arm do
      url "https://github.com/strantalis/workset/releases/download/v#{version}/workset_#{version}_darwin_arm64.tar.gz"
      sha256 "1f95cb82db9eca88c6c1dbdda5d460b1837f5a4b698f3ef983ef4325192434ba"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/strantalis/workset/releases/download/v#{version}/workset_#{version}_linux_amd64.tar.gz"
      sha256 "737f4dd9786d2017eab61edbecd0b31581aae03315ec9880dc2174f8c39a3f5a"
    end
    on_arm do
      url "https://github.com/strantalis/workset/releases/download/v#{version}/workset_#{version}_linux_arm64.tar.gz"
      sha256 "9021ed6dd238b3450e27aff5655736325544a256cde936cb2cafcbd20a6a9bf2"
    end
  end

  # No zap stanza required
end
